name: Build for macOS and iOS

on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  project-id: com.adilhanney.saber

jobs:
  build:
    name: Build for macOS and iOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Setup Flutter
        run: |
          flutter config --enable-macos-desktop
          flutter pub get

      - name: Build for iOS
        run: flutter build ios --no-codesign

      - name: Compress iOS build
        run: |
          pushd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r Saber.ipa Payload
          popd

      - name: Upload iOS build
        uses: actions/upload-artifact@v3
        with:
          name: Saber-iOS-Archive
          path: build/ios/iphoneos/Saber.ipa

      - name: Build for macOS
        run: flutter build macos

      - name: Compress macOS build
        run: |
          pushd build/macos/Build/Products/Release
          zip -r Saber.app.zip Saber.app
          popd

      - name: Upload macOS build
        uses: actions/upload-artifact@v3
        with:
          name: Saber-macOS-Archive
          path: build/macos/Build/Products/Release/Saber.app.zip
