name: Build for iOS

on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  project-id: com.adilhanney.saber

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      buildName: ${{ steps.get_version.outputs.buildName }}
      buildNumber: ${{ steps.get_version.outputs.buildNumber }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          # get buildName from lib/data/version.dart
          buildName=$(grep -oP '(?<=buildName = ").*(?=")' lib/data/version.dart)
          echo "buildName=$buildName" >> $GITHUB_OUTPUT

          # get buildNumber from lib/data/version.dart
          buildNumber=$(grep -oP '(?<=buildNumber = ).*(?=;)' lib/data/version.dart)
          echo "buildNumber=$buildNumber" >> $GITHUB_OUTPUT

  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    needs: get-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf android
          rm -rf appimage
          rm -rf assets_raw
          rm -rf flatpak
          rm -rf installers
          rm -rf integration_test
          rm -rf linux
          rm -rf macos
          rm -rf metadata
          rm -rf snap
          rm -rf submodules
          rm -rf test
          rm -rf windows

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - run: flutter pub get

      - name: Build for iOS
        run: flutter build ios --no-codesign

      - name: Compress iOS build
        id: compress
        run: |
          ipaName="Saber_v${{ needs.get-version.outputs.buildName }}_${{ needs.get-version.outputs.buildNumber }}.ipa"
          echo "ipaName=$ipaName" >> $GITHUB_OUTPUT

          pushd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r $ipaName Payload
          popd

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Saber-iOS-Archive
          path: build/ios/iphoneos/${{ steps.compress.outputs.ipaName }}

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/${{ steps.compress.outputs.ipaName }}
