name: Build for macOS

# Using instructions from
# https://docs.flutter.dev/deployment/macos#create-a-build-archive-with-codemagic-cli-tools

on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  project-id: com.adilhanney.saber

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      buildName: ${{ steps.get_version.outputs.buildName }}
      buildNumber: ${{ steps.get_version.outputs.buildNumber }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: |
          # get buildName from lib/data/version.dart
          buildName=$(grep -oP '(?<=buildName = ").*(?=")' lib/data/version.dart)
          echo "buildName=$buildName" >> $GITHUB_OUTPUT

          # get buildNumber from lib/data/version.dart
          buildNumber=$(grep -oP '(?<=buildNumber = ).*(?=;)' lib/data/version.dart)
          echo "buildNumber=$buildNumber" >> $GITHUB_OUTPUT

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    needs: get-version
    env:
      APP_STORE_CONNECT_ISSUER_ID: ${{secrets.APP_STORE_CONNECT_ISSUER_ID}}
      APP_STORE_CONNECT_KEY_IDENTIFIER: ${{secrets.APP_STORE_CONNECT_KEY_IDENTIFIER}}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{secrets.APP_STORE_CONNECT_PRIVATE_KEY}}
      APP_STORE_CERTIFICATE_KEY: ${{secrets.APP_STORE_CERTIFICATE_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf android
          rm -rf appimage
          rm -rf assets_raw
          rm -rf flatpak
          rm -rf installers
          rm -rf integration_test
          rm -rf ios
          rm -rf linux
          rm -rf metadata
          rm -rf snap
          rm -rf submodules
          rm -rf test
          rm -rf windows

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install Codemagic CLI Tools
        run: pip3 install codemagic-cli-tools

      - name: Setup keychain
        run: |
          keychain initialize

          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --certificate-key=@env:APP_STORE_CERTIFICATE_KEY \
            --create

          app-store-connect list-certificates \
            --type MAC_INSTALLER_DISTRIBUTION \
            --certificate-key=@env:APP_STORE_CERTIFICATE_KEY \
            --save
    
          keychain add-certificates

          xcode-project use-profiles

      - run: flutter pub get
      - run: find . -name "Podfile" -execdir pod install \;

      - name: Build for macOS
        run: flutter build macos

      - name: Compress macOS build
        id: compress
        run: |
          zipName="Saber_v${{ needs.get-version.outputs.buildName }}_${{ needs.get-version.outputs.buildNumber }}.app.zip"
          echo "zipName=$zipName" >> $GITHUB_OUTPUT

          pushd build/macos/Build/Products/Release
          zip -r $zipName Saber.app
          popd

      - name: Restore keychain
        run: |
          keychain use-login

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Saber-macOS-Archive
          path: build/macos/Build/Products/Release/${{ steps.compress.outputs.zipName }}

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/macos/Build/Products/Release/${{ steps.compress.outputs.zipName }}
