name: Run onyxsdk_pen tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/onyxsdk_pen/**'
  push:
    paths:
      - 'packages/onyxsdk_pen/**'

jobs:
  run-tests:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libsecret-1-dev libjsoncpp-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:'

      - name: Run tests (packages/onyxsdk_pen)
        working-directory: packages/onyxsdk_pen
        run: flutter test
