name: Run tests

on:
  # Enable manual run
  workflow_dispatch:
  pull_request:
  push:

env:
  project-id: com.adilhanney.saber

jobs:
  run-tests:
    name: Run Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf assets_raw
          rm -rf submodules

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libsecret-1-dev libjsoncpp-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Prepare environment for tests
        run: |
          IS_MAIN_REPO=$(expr "$GITHUB_REPOSITORY" = "adil192/saber")
          IS_MAIN_BRANCH=$(expr "$GITHUB_REF_NAME" = "main")
          MAINTENANCE_CHECKS_ENABLED=$(expr "$IS_MAIN_REPO" "&" "$IS_MAIN_BRANCH")
          echo "MAINTENANCE_CHECKS_ENABLED=$(test $MAINTENANCE_CHECKS_ENABLED -eq 1 && echo true || echo false)" >> $GITHUB_ENV

      - name: Run tests
        id: tests
        run: |
          flutter test \
            --reporter expanded \
            --coverage \
            --dart-define=maintenanceChecksEnabled="${{ env.MAINTENANCE_CHECKS_ENABLED }}"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info

      - name: Run tests (packages/onyxsdk_pen)
        working-directory: packages/onyxsdk_pen
        run: flutter test --reporter expanded
