name: Build for Windows

on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  project-id: com.adilhanney.saber

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rm -rf android
          rm -rf appimage
          rm -rf assets_raw
          rm -rf flatpak
          rm -rf integration_test
          rm -rf ios
          rm -rf linux
          rm -rf macos
          rm -rf metadata
          rm -rf snap
          rm -rf submodules
          rm -rf test
          rm -rf web

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Inno Setup
        run: choco install innosetup

      - run: flutter pub get

      - name: Build Windows
        run: flutter build apk

      - name: Build Windows Installer
        run: |
          ISCC.exe installers/desktop_inno_script.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Saber-Windows
          path: installers/SaberInstaller.exe

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installers/SaberInstaller.exe
