name: Build for Windows

on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  project-id: com.adilhanney.saber

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove unneeded files
        run: |
          rmdir /s /q android
          rmdir /s /q appimage
          rmdir /s /q assets_raw
          rmdir /s /q flatpak
          rmdir /s /q integration_test
          rmdir /s /q ios
          rmdir /s /q linux
          rmdir /s /q macos
          rmdir /s /q metadata
          rmdir /s /q snap
          rmdir /s /q submodules
          rmdir /s /q test
          rmdir /s /q web

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Inno Setup
        run: choco install innosetup

      - run: flutter pub get

      - name: Build Windows
        run: flutter build apk

      - name: Build Windows Installer
        run: |
          ISCC.exe installers/desktop_inno_script.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Saber-Windows
          path: installers/SaberInstaller.exe

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installers/SaberInstaller.exe
